// packages/types/src/index.ts
import { z } from "zod";

export const AIResponseSchema = z.object({
  planTitle: z.string().min(1).default("Untitled Plan"),
  
  // Tasks generated by AI - highly structured now
  tasks: z
    .array(
      z.object({
        title: z.string().min(1),
        description: z.string().optional().default(""),
        dueDate: z
          .string()
          .refine((val) => !isNaN(Date.parse(val)), {
            message: "Invalid date format, expected ISO string",
          })
          .optional(),
        estimatedPomodoros: z.number().min(1).max(10).default(1)
      })
    )
    .min(0)
    .default([]),
});

export type AIResponse = z.infer<typeof AIResponseSchema>;

// New Adjust Logic
export const AIAdjustmentResponseSchema = z.object({
  updatedTasks: z.array(
    z.object({
      taskId: z.string(),
      newTitle: z.string().optional(),
      newEstimatedPomodoros: z.number().optional(),
      splitIntoSubtasks: z.array(
        z.object({
          title: z.string(),
          estimatedPomodoros: z.number()
        })
      ).optional()
    })
  )
});

export type AIAdjustmentResponse = z.infer<typeof AIAdjustmentResponseSchema>;
